### ISSUE TITLE
Suggestions for the list

### ISSUE THREAD

**Issue by JohannesGaessler** [Maks-s/sd-akashic#11]
I am investigating the effects of things like square brackets and exclamation marks using statistical methods:

https://github.com/JohannesGaessler/stable-diffusion-tools/tree/master/emphasis

There is also a wiki associated with the Stable Diffusion threads on 4chan's technolo/g/y board:

https://wiki.installgentoo.com/wiki/Stable_Diffusion

**Comment by Maks-s** [comment]
This is very interesting, I'll add them when I get the time

**Comment by Maks-s** [comment]
Done !

**Comment by Maks-s** [comment]
Oh right, I'll rename it to "4chan /g/ wiki"
