### ISSUE TITLE
[RELEASE] Stable Diffusion V1.5 Artist Study (with images)

### ISSUE THREAD

**Issue by mashonoid** [Maks-s/sd-akashic#13]
Made a database of Artists modifiers for SD 1.5
The database contains :- 
Images of Artist work | Image of the base prompt (w/o modifier) | Image of the prompt (w/ modifier)

Here it is :-
https://docs.google.com/spreadsheets/d/1SRqJ7F_6yHVSOeCi3U82aA448TqEGrUlRrLLZ51abLg/edit?usp=sharing

**Comment by Maks-s** [comment]
Done !
