### ISSUE TITLE
Improving old 3D renders

### ISSUE THREAD

**Issue by rafaelcastrocouto** [Maks-s/sd-akashic#23]
I've written this small article about how architects and designers might use SD to improve their old work, I hope you like it and add it to your amazing list!

https://dev.to/rafaelcastrocouto/improving-old-3d-renders-with-ai-and-sd-jpc

**Comment by Maks-s** [comment]
Done, thank you for your contribution to SD's community :)

**Comment by Maks-s** [comment]
fixed !
