### ISSUE TITLE
"Wonderflex's photography terms studies" links to wrong URL

### ISSUE THREAD

**Issue by Quanyails** [Maks-s/sd-akashic#24]
I just noticed that the link with the text "Wonderflex's photography terms studies" leads to the same URL as the link with the text "Test of seeds, clothing, and clothing modifications", which doesn't seem intentional. Would you be able to update the link? I think [this post](https://www.reddit.com/r/StableDiffusion/comments/x8i5co/a_test_of_photography_related_terms_on_kim/) is what the link was meant to link to.

**Comment by Maks-s** [comment]
Oh my, I didn't notice this. Thank you :)
