### ISSUE TITLE
Maybe review the resources to ensure a certain quality?

### ISSUE THREAD

**Issue by dkl78167816** [Maks-s/sd-akashic#8]
Some resources don't do anything, don't say anything, don't deserve to be included in .

![image](https://user-images.githubusercontent.com/32244400/188259438-e312dc04-be02-4f3a-bc39-10478f5bd607.png)

That is my tiny research on sampler, a little work that has nothing to say, but some resources are worse than that

**Comment by Maks-s** [comment]
Can you provide examples of useless resources please ? I'll review if they're really worthless and delete accordingly

**Comment by dkl78167816** [comment]
> Can you provide examples of useless resources please ? I'll review if they're really worthless and delete accordingly

Some of the modifier studies, just just lists a few graphs without any convinced conclusion or experimental basis
